
import { LeadershipMistake, LeadershipPart } from './types';

export const LEADERSHIP_DATA: LeadershipMistake[] = [
  // Phần 1: Tư duy & Bản thân Lãnh đạo
  { id: 1, part: "Phần 1", category: LeadershipPart.PART1, mistake: "Ngừng học hỏi: Nghĩ rằng mình đã biết đủ khi đạt được vị trí quản lý.", solution: "Nguyên lý Nắp Chặn: Khả năng lãnh đạo xác định mức độ hiệu quả của tổ chức. Bạn phải liên tục nâng cao 'nắp chặn' của mình." },
  { id: 2, part: "Phần 1", category: LeadershipPart.PART1, mistake: "Dựa vào chức danh: Ra lệnh dựa trên quyền lực vị trí ('Làm đi vì tôi là sếp').", solution: "Cấp độ Lãnh đạo 1 (Chức danh): Chuyển sang Cấp độ 2 (Sự chấp thuận) bằng cách xây dựng mối quan hệ để nhân viên muốn theo bạn." },
  { id: 3, part: "Phần 1", category: LeadershipPart.PART1, mistake: "Thiếu tính chính trực: Nói một đằng làm một nẻo, hứa nhưng không giữ lời.", solution: "Nguyên lý Niềm Tin: Niềm tin là nền tảng của lãnh đạo. Hãy xây dựng uy tín bằng sự nhất quán và trung thực." },
  { id: 4, part: "Phần 1", category: LeadershipPart.PART1, mistake: "Cái tôi quá lớn: Không dám nhận sai, sợ nhân viên giỏi hơn mình.", solution: "Nguyên lý Trao Quyền: Chỉ những nhà lãnh đạo an toàn mới dám trao quyền lực cho người khác. Hãy khiêm tốn." },
  { id: 5, part: "Phần 1", category: LeadershipPart.PART1, mistake: "Thiếu kỷ luật bản thân: Quản lý người khác nhưng buông thả chính mình.", solution: "Lãnh đạo bản thân trước: Bạn không thể dẫn dắt người khác đi xa hơn nơi bạn đã đến." },
  { id: 6, part: "Phần 1", category: LeadershipPart.PART1, mistake: "Tư duy nạn nhân: Đổ lỗi cho hoàn cảnh hoặc nhân viên khi thất bại.", solution: "Chịu trách nhiệm 100%: Lãnh đạo là người chịu trách nhiệm cuối cùng. Nhìn vào gương trước khi nhìn ra cửa sổ." },
  { id: 7, part: "Phần 1", category: LeadershipPart.PART1, mistake: "Làm việc đơn độc: Cố gắng tự giải quyết mọi vấn đề hệ thống ('Người hùng đơn độc').", solution: "Nguyên lý Nội bộ: Tiềm năng của lãnh đạo được quyết định bởi những người thân cận nhất với họ." },
  { id: 8, part: "Phần 1", category: LeadershipPart.PART1, mistake: "Sợ thay đổi: Giữ nguyên quy trình cũ vì 'xưa giờ vẫn làm thế'.", solution: "Lãnh đạo là thay đổi: Nếu không có thay đổi, không cần lãnh đạo. Hãy là tác nhân của sự đổi mới." },
  { id: 9, part: "Phần 1", category: LeadershipPart.PART1, mistake: "Thiếu năng lượng: Xuất hiện trước đội ngũ với vẻ mệt mỏi, tiêu cực.", solution: "Truyền lửa: Lãnh đạo là người giữ nhịp cảm xúc. Thái độ của bạn sẽ lan truyền xuống cả hệ thống." },
  { id: 10, part: "Phần 1", category: LeadershipPart.PART1, mistake: "Quản lý vi mô (Micromanagement): Can thiệp vào từng chi tiết nhỏ.", solution: "Tập trung vào bức tranh lớn: Quản lý quy trình, lãnh đạo con người. Hãy tin tưởng và kiểm tra định kỳ thay vì soi mói." },
  
  // Phần 2: Kết nối & Phát triển Con người
  { id: 11, part: "Phần 2", category: LeadershipPart.PART2, mistake: "Không lắng nghe: Chỉ đạo thao thao bất tuyệt mà không nghe phản hồi.", solution: "Nguyên lý Kết nối: Chạm vào trái tim trước khi nhờ vả đôi tay. Lắng nghe để thấu hiểu, không phải để đối đáp." },
  { id: 12, part: "Phần 2", category: LeadershipPart.PART2, mistake: "Tuyển dụng sai người: Tuyển người giống mình hoặc tuyển vội vàng để lấp chỗ trống.", solution: "Nguyên lý Thu hút: Bạn là ai thì bạn hút người đó. Muốn tuyển người giỏi, bạn phải giỏi trước." },
  { id: 13, part: "Phần 2", category: LeadershipPart.PART2, mistake: "Giữ người yếu kém: Vì nể nang mà không sa thải nhân viên 'độc hại'.", solution: "Nguyên lý Táo thối: Một thái độ tồi tệ sẽ làm hỏng cả đội ngũ. Bảo vệ đội ngũ bằng cách loại bỏ nhân tố tiêu cực." },
  { id: 14, part: "Phần 2", category: LeadershipPart.PART2, mistake: "Không đào tạo kế thừa: Giữ bí quyết nghề nghiệp cho riêng mình.", solution: "Nguyên lý Di sản: Giá trị của lãnh đạo được đo bằng sự kế thừa. Thành công là khi không có bạn, hệ thống vẫn chạy tốt." },
  { id: 15, part: "Phần 2", category: LeadershipPart.PART2, mistake: "Đối xử cào bằng: Thưởng phạt như nhau giữa người giỏi và người lười.", solution: "Lãnh đạo công bằng, không cào bằng: Đầu tư thời gian vào top 20% nhân sự xuất sắc nhất (Nguyên lý Pareto)." },
  { id: 16, part: "Phần 2", category: LeadershipPart.PART2, mistake: "Chỉ trích công khai: Quát mắng nhân viên trước mặt người khác.", solution: "Khen ngợi công khai, góp ý riêng tư: Bảo vệ lòng tự trọng của nhân viên để giữ được sự trung thành của họ." },
  { id: 17, part: "Phần 2", category: LeadershipPart.PART2, mistake: "Thiếu sự khích lệ: Chỉ liên hệ khi có việc cần hoặc khi có lỗi sai.", solution: "Nguyên lý Khích lệ: Con người thèm khát sự công nhận. Hãy bắt quả tang nhân viên làm đúng và khen ngợi ngay." },
  { id: 18, part: "Phần 2", category: LeadershipPart.PART2, mistake: "Giao việc không giao quyền: Bắt nhân viên chịu trách nhiệm nhưng không cho họ quyền quyết định.", solution: "Trao quyền trọn vẹn: Khi giao trách nhiệm, phải giao kèm nguồn lực và quyền hạn tương ứng." },
  { id: 19, part: "Phần 2", category: LeadershipPart.PART2, mistake: "Không quan tâm đời sống nhân viên: Chỉ coi nhân viên là công cụ kiếm tiền.", solution: "Cấp độ Lãnh đạo 2 (Quan hệ): Mọi người không quan tâm bạn biết nhiều thế nào cho đến khi họ biết bạn quan tâm họ bao nhiêu." },
  { id: 20, part: "Phần 2", category: LeadershipPart.PART2, mistake: "Kỳ vọng sai lệch: Mong đợi nhân viên làm việc như một lãnh đạo khi chưa đào tạo họ.", solution: "Nguyên lý Quy trình: Lãnh đạo phát triển hàng ngày, không phải trong một ngày. Hãy kiên nhẫn với sự trưởng thành của họ." },

  // Phần 3: Tầm nhìn & Định hướng Chiến lược
  { id: 21, part: "Phần 3", category: LeadershipPart.PART3, mistake: "Tầm nhìn mù mờ: Nhân viên không biết công ty sẽ đi về đâu trong 3-5 năm tới.", solution: "Nguyên lý La Bàn: Ai cũng có thể lái tàu, nhưng cần người lãnh đạo để vạch ra hải trình. Tầm nhìn phải rõ ràng." },
  { id: 22, part: "Phần 3", category: LeadershipPart.PART3, mistake: "Bận rộn mù quáng: Làm việc 12-14 tiếng nhưng hiệu quả thấp.", solution: "Nguyên lý Ưu tiên: Hoạt động không có nghĩa là thành tựu. Tập trung vào những việc tạo ra 80% kết quả." },
  { id: 23, part: "Phần 3", category: LeadershipPart.PART3, mistake: "Phản ứng thay vì chủ động: Chờ sự cố xảy ra mới đi giải quyết (chữa cháy).", solution: "Tư duy hệ thống: Lường trước vấn đề (Tiên liệu). Người lãnh đạo nhìn thấy nhiều hơn và xa hơn người khác." },
  { id: 24, part: "Phần 3", category: LeadershipPart.PART3, mistake: "Truyền thông kém: Nghĩ rằng 'nói một lần là họ đã hiểu'.", solution: "Truyền thông đa kênh: Tầm nhìn bị 'rò rỉ' theo thời gian. Phải nhắc lại tầm nhìn liên tục (mỗi 21 ngày)." },
  { id: 25, part: "Phần 3", category: LeadershipPart.PART3, mistake: "Ra quyết định chậm trễ: Do dự khiến cơ hội trôi qua.", solution: "Nguyên lý Thời điểm: Làm đúng việc nhưng sai thời điểm vẫn là thất bại. Quyết đoán dựa trên trực giác và dữ liệu." },
  { id: 26, part: "Phần 3", category: LeadershipPart.PART3, mistake: "Không có thước đo: Quản lý cảm tính, không có KPI hay dữ liệu.", solution: "Thực tế hoá: Chúng ta không thể quản lý những gì không đo lường được. Hãy đối diện với sự thật trần trụi." },
  { id: 27, part: "Phần 3", category: LeadershipPart.PART3, mistake: "Ôm đồm mọi việc: Việc gì cũng muốn nhúng tay vào.", solution: "Nghệ thuật uỷ quyền: Nếu ai đó có thể làm tốt 80% bằng bạn, hãy giao việc đó cho họ." },
  { id: 28, part: "Phần 3", category: LeadershipPart.PART3, mistake: "Thiếu tập trung: Theo đuổi quá nhiều mục tiêu cùng lúc.", solution: "Sức mạnh của sự tập trung: Để đi xa, bạn phải bỏ bớt hành lý. Chọn 1-3 mục tiêu tối thượng." },
  { id: 29, part: "Phần 3", category: LeadershipPart.PART3, mistake: "Đánh giá thấp đối thủ/rủi ro: Quá tự tin vào thành công quá khứ.", solution: "Nguyên lý Chiến thắng: Đừng để thành công hôm qua ru ngủ bạn. Luôn khiêm tốn và cảnh giác." },
  { id: 30, part: "Phần 3", category: LeadershipPart.PART3, mistake: "Họp hành vô bổ: Tổ chức quá nhiều cuộc họp không có kết luận.", solution: "Hiệu suất: Cuộc họp chỉ nên diễn ra để quyết định hoặc thông báo quan trọng. Tôn trọng thời gian của đội ngũ." },

  // Phần 4: Văn hóa & Vận hành Hệ thống
  { id: 31, part: "Phần 4", category: LeadershipPart.PART4, mistake: "Văn hóa đổ lỗi: Nhân viên sợ sai, giấu giếm lỗi lầm.", solution: "Văn hóa an toàn: Khuyến khích sự minh bạch. 'Thất bại về phía trước' – sai lầm là bài học, không phải án tử." },
  { id: 32, part: "Phần 4", category: LeadershipPart.PART4, mistake: "Mất đà tăng trưởng: Để tổ chức trì trệ, không có khí thế.", solution: "Nguyên lý Động lượng: Động lượng là bạn thân của lãnh đạo. Hãy tạo ra những thắng lợi nhỏ để khích lệ tinh thần." },
  { id: 33, part: "Phần 4", category: LeadershipPart.PART4, mistake: "Hệ thống phức tạp: Quy trình rườm rà, quan liêu.", solution: "Đơn giản hóa: Lãnh đạo giỏi là người biến điều phức tạp thành đơn giản để ai cũng thực hiện được." },
  { id: 34, part: "Phần 4", category: LeadershipPart.PART4, mistake: "Thiếu sự hy sinh: Lãnh đạo muốn hưởng thụ nhiều hơn cống hiến.", solution: "Nguyên lý Hy sinh: Để tiến lên, bạn phải từ bỏ. Lãnh đạo càng cao, quyền lợi càng ít, trách nhiệm càng nhiều." },
  { id: 35, part: "Phần 4", category: LeadershipPart.PART4, mistake: "Không ăn mừng chiến thắng: Đạt mục tiêu xong lao ngay vào việc mới.", solution: "Nuôi dưỡng tinh thần: Dành thời gian ghi nhận chiến thắng để tái tạo năng lượng cho đội ngũ." },
  { id: 36, part: "Phần 4", category: LeadershipPart.PART4, mistake: "Dung túng sự tầm thường: Chấp nhận kết quả 'tạm được'.", solution: "Tiêu chuẩn xuất sắc: Lãnh đạo là người nâng cao tiêu chuẩn. Đừng thỏa hiệp với sự trung bình." },
  { id: 37, part: "Phần 4", category: LeadershipPart.PART4, mistake: "Thiếu sự gắn kết: Các phòng ban kèn cựa, không hỗ trợ nhau (Silos).", solution: "Tư duy Hợp tác: Một là con số quá nhỏ để làm nên điều vĩ đại. Phá bỏ rào cản phòng ban." },
  { id: 38, part: "Phần 4", category: LeadershipPart.PART4, mistake: "Hứa hão: Hứa thưởng nhưng không thực hiện.", solution: "Uy tín: Một lời hứa không thực hiện là một vết nứt trong nền móng lãnh đạo." },
  { id: 39, part: "Phần 4", category: LeadershipPart.PART4, mistake: "Quên đi khách hàng: Tập trung quá nhiều vào quy trình nội bộ mà quên ai trả tiền.", solution: "Phục vụ: Lãnh đạo phục vụ nhân viên, nhân viên phục vụ khách hàng." },
  { id: 40, part: "Phần 4", category: LeadershipPart.PART4, mistake: "Không chuẩn bị cho khủng hoảng: Lạc quan thái quá.", solution: "Tư duy dự phòng: Hy vọng điều tốt nhất, nhưng chuẩn bị cho điều tệ nhất." },

  // Phần 5: Phát triển Lãnh đạo kế cận
  { id: 41, part: "Phần 5", category: LeadershipPart.PART5, mistake: "Sợ nhân viên giỏi hơn mình: 'Đè' người tài xuống.", solution: "Lãnh đạo an toàn: Thành công của bạn là khi nhân viên vượt qua bạn. Hãy nâng họ lên vai bạn." },
  { id: 42, part: "Phần 5", category: LeadershipPart.PART5, mistake: "Không Mentor (Cố vấn): Để nhân viên tự bơi.", solution: "Kèm cặp 1-1: Dành thời gian chất lượng cho những nhân tố tiềm năng nhất (Inner Circle)." },
  { id: 43, part: "Phần 5", category: LeadershipPart.PART5, mistake: "Giữ ghế quá lâu: Không chịu rời vị trí khi đã hết nhiệt huyết.", solution: "Chuyển giao: Biết thời điểm để bước sang một bên và nhường sân khấu cho thế hệ sau." },
  { id: 44, part: "Phần 5", category: LeadershipPart.PART5, mistake: "Chỉ dạy kỹ năng, không dạy tư duy: Nhân viên làm được việc nhưng không biết cách nghĩ.", solution: "Nhân bản tư duy: Dạy họ 'cách câu cá' (tư duy giải quyết vấn đề) thay vì chỉ đưa 'cần câu' (công cụ)." },
  { id: 45, part: "Phần 5", category: LeadershipPart.PART5, mistake: "Tạo ra người theo sau (Followers): Muốn mọi người vâng lời.", solution: "Tạo ra Lãnh đạo (Leaders): Mục tiêu tối thượng là tạo ra những nhà lãnh đạo khác, không phải đàn em." },
  { id: 46, part: "Phần 5", category: LeadershipPart.PART5, mistake: "Đánh giá qua vẻ bề ngoài: Bỏ qua những nhân tố tiềm năng nhưng trầm lặng.", solution: "Nhìn xuyên thấu: Nhìn thấy tiềm năng ở người khác trước khi chính họ nhìn thấy điều đó." },
  { id: 47, part: "Phần 5", category: LeadershipPart.PART5, mistake: "Thiếu kiên nhẫn khi đào tạo: Muốn có kết quả ngay.", solution: "Đầu tư dài hạn: Phát triển con người giống như trồng rừng, cần thời gian và sự kiên trì." },
  { id: 48, part: "Phần 5", category: LeadershipPart.PART5, mistake: "Không chia sẻ quyền lực: Giữ hết quyền quyết định quan trọng.", solution: "Chia sẻ gánh nặng: Chia sẻ quyền lực giúp tăng sức mạnh của tổ chức, không làm giảm quyền lực của bạn." },
  { id: 49, part: "Phần 5", category: LeadershipPart.PART5, mistake: "Quên mất 'Tại sao': Chỉ chỉ đạo 'Làm cái gì' và 'Làm thế nào'.", solution: "Bắt đầu với câu hỏi Tại sao: Truyền cảm hứng bằng ý nghĩa công việc để tạo động lực nội tại." },
  { id: 50, part: "Phần 5", category: LeadershipPart.PART5, mistake: "Không để lại di sản: Khi rời đi, tổ chức sụp đổ.", solution: "Di sản: Bạn sống trong mọi người qua những gì bạn đã dạy họ. Hãy xây dựng để trường tồn." }
];
